apiVersion: v1
kind: Namespace
metadata:
   name: dev

---

apiVersion: v1
kind: Namespace
metadata:
  name: qa

---
apiVersion: v1
kind: Namespace
metadata:
  name: test

---


apiVersion: v1
kind: Namespace
metadata:
  name: prod
---

apiVersion: v1
kind: Namespace
metadata:
  name: stage
---

apiVersion: v1
kind: Namespace
metadata:
  name: tools
---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---

apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: dev
spec:
  containers:
  - name: redis
    image: redis
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do date; sleep 3; done']
---



apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx
---


apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: qa
spec:
  containers:
  - name: redis
    image: redis
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do date; sleep 3; done']
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: qa
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: prod
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: stage
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: tools
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: monitoring
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
---

apiVersion: v1
kind: Pod
metadata:
  name: kucc1
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  - image: redis
    name: redis
    imagePullPolicy: IfNotPresent
  - name: memcached
    image: memcached
  - name: consul
    image: hashicorp/consul
---

apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: default
spec:
  containers:
  - name: mysql
    image: mysql
    env:
    - name:  MYSQL_ROOT_PASSWORD
      value: kaizen
  nodeSelector:
    type: worker1
---

apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  namespace: default
spec:
  containers:
  - name: mariadb
    image: mariadb
    env:
    - name:  MARIADB_ROOT_PASSWORD
      value: kaizen
  nodeSelector:
    type: worker2

---

apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default   
  labels:
    team: devops
    company: kaizen
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do date; sleep 3; done']
